//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BootStrap4.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DangKyTin
    {
        public int MaDangKy { get; set; }
        public string TenTaiKhoan { get; set; }
        public int MaMon { get; set; }
        public Nullable<System.DateTime> NgayTao { get; set; }
        public Nullable<System.DateTime> NgaySua { get; set; }
        public string NguoiTao { get; set; }
        public string NguoiSua { get; set; }
    
        public virtual TaiKhoan TaiKhoan { get; set; }
        public virtual MonHoc MonHoc { get; set; }
    }
}
